[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = [
  "npm install -g corepack@0.24.1 && corepack enable",
  "yarn install --frozen-lockfile"
]

[phases.build]
cmds = ["npx turbo run build"]

[phases.start]
cmd = "yarn start"